import { chromium } from 'playwright-core';
const browser = await chromium.connectOverCDP('http://localhost:9222');
const ctx = browser.contexts()[0];
const page = await ctx.newPage();
await page.goto('https://old.reddit.com/r/IndianStockMarket/search?q=zerodha&restrict_sr=on&sort=new&t=year', { waitUntil: 'domcontentloaded', timeout: 30000 });
await page.waitForTimeout(3000);
const title = await page.title();
const results = await page.locator('.search-result-link').count();
const blocked = await page.locator('text=/blocked|whoa there|network policy/i').count();
console.log(JSON.stringify({ title, results, blocked }));
await page.close();
await browser.close();
